// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-E1BhHiAnmsUKYvnRz6FAShLX3JebWGQ',
    appId: '1:148890978662:web:2781866192ba691ff5e0a7',
    messagingSenderId: '148890978662',
    projectId: 'pi-phone-5ac3b',
    authDomain: 'pi-phone-5ac3b.firebaseapp.com',
    storageBucket: 'pi-phone-5ac3b.firebasestorage.app',
    measurementId: 'G-WHRFPJJBPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsjq4MhGduNJge3VaZJoW1t1V6MZgpHCs',
    appId: '1:148890978662:android:6f4d51df83265669f5e0a7',
    messagingSenderId: '148890978662',
    projectId: 'pi-phone-5ac3b',
    storageBucket: 'pi-phone-5ac3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTToGEyTV0VppIm5IcbNaEAKdHP5j_xtI',
    appId: '1:148890978662:ios:0cf3990e7505bdd6f5e0a7',
    messagingSenderId: '148890978662',
    projectId: 'pi-phone-5ac3b',
    storageBucket: 'pi-phone-5ac3b.firebasestorage.app',
    iosBundleId: 'com.example.intercom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTToGEyTV0VppIm5IcbNaEAKdHP5j_xtI',
    appId: '1:148890978662:ios:0cf3990e7505bdd6f5e0a7',
    messagingSenderId: '148890978662',
    projectId: 'pi-phone-5ac3b',
    storageBucket: 'pi-phone-5ac3b.firebasestorage.app',
    iosBundleId: 'com.example.intercom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-E1BhHiAnmsUKYvnRz6FAShLX3JebWGQ',
    appId: '1:148890978662:web:ce328db8388668faf5e0a7',
    messagingSenderId: '148890978662',
    projectId: 'pi-phone-5ac3b',
    authDomain: 'pi-phone-5ac3b.firebaseapp.com',
    storageBucket: 'pi-phone-5ac3b.firebasestorage.app',
    measurementId: 'G-GECG2MTHLC',
  );
}
